# Generated by Django 5.0.1 on 2024-06-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0021_userinfo_shortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
